export const BOT_NAME = "GPSC Dental Class-2 Bot";

export const CALLBACKS = {
  MENU_STUDY: "MENU_STUDY",
  MENU_TEST: "MENU_TEST",
  MENU_REPORT: "MENU_REPORT",
  MENU_SETTINGS: "MENU_SETTINGS",
  MENU_ADMIN: "MENU_ADMIN",
  MENU_HELP: "MENU_HELP",
};
